### ISSUE TITLE
Safe by default HTTPS

### ISSUE THREAD

**Issue by ericmj** [ericmj/xhttp#21]
* [x] Safe by default `:ssl` options
* [x] Hostname verification for older OTP versions
* [x] Partial chains
* [x] ~~Ship with Mozilla CA store~~ Use castore library instead
* [x] ~~Task for updating CA store~~ Invalid now that we use a dependency instead
* [ ] Extra credit: add support for nested SSL sessions in OTP

**Comment by ericmj** [comment]
For reference https://github.com/hexpm/hex/tree/master/lib/hex/http

**Comment by voltone** [comment]
What minimum OTP version did you have in mind, @ericmj? The `pkix_verify_hostname/2` function was introduced in 19.3, a year ago, though it wasn't enabled by default. Is it worth supporting older versions with a custom implementation? Or do you just want to enable the check when on 19.3?

**Comment by ericmj** [comment]
This library may be included in Elixir so we need to support at least 19.0, it will also be used in Hex which supports 17.0. The implementation in Hex is currently based on https://github.com/deadtrickster/ssl_verify_fun.erl but I would like to bring a custom implementation of `pkix_verify_hostname/2` to xhttp.

**Comment by ericmj** [comment]
@voltone 

In hex we have a callback function for handling for partial chains [1]. We need this in xhttp as well, right?

We are also missing some other default options we use in hex;`:server_name_indication`, `:reuse_sessions`, `:honor_cipher_order` and `:ciphers`.

I think we can default to set `:server_name_indication` to the http host. Would it make sense to provide a default set of ciphers, in hex we use this [2], maybe we should provide some "profiles" with cipher sets users can pick from.

Any of these defaults we should not add and are we missing any other sensible defaults?

[1] https://github.com/hexpm/hex/blob/master/lib/hex/http/ssl.ex#L89
[2] https://github.com/hexpm/hex/blob/master/lib/hex/http/ssl.ex#L6

**Comment by voltone** [comment]
We also need to decide on the TLS version(s) to enable by default (I'd say >=1.2), and set the `:secure_renegotiate` flag (defaults to `false` prior to OTP 21).

As for ciphers, the current Hex defaults include 3DES, RSA key exchange, and CBC mode. I would say all of these should be opt-in, as they have known issues. OTP 21 agrees, except for CBC. The H2 blacklist eliminates all of those, so right now the defaults would seem pretty good. We could consider adding a 'compatibility' cipher suite, as was done in Plug. Do you want to open a new issue to discuss this further?

I'll work on partial chains next. There are two use-cases to consider: cross-signed CAs and pinning on intermediate CAs. The former is critical to any HTTP client, but is not handled correctly by `:ssl` by default.

**Comment by ericmj** [comment]
> The H2 blacklist eliminates all of those, so right now the defaults would seem pretty good. 

We apply the blacklist for both H1 and H2, according to the specs we only have to apply it for H2 but it seems reasonable to apply it for both. If the blacklist we have today eliminates the problematic ciphers then I think we can use that for now and punt on cipher suites until later.

> :honor_cipher_order is a server option, so it is not applicable.

Oh :)

> I'll work on partial chains next.

:pray:

**Comment by ericmj** [comment]
Closing in favor of https://github.com/ericmj/xhttp/pull/46.

There's still a lot that can be improved in the HTTPS handling but this is using secure defaults and good enough for a first release.
