### ISSUE TITLE
Proxying

### ISSUE THREAD

**Issue by ericmj** [ericmj/xhttp#22]
* [ ] CONNECT tunnel HTTP2 (in progress by @whatyouhide)
* [x] CONNECT tunnel HTTP1
* [ ] AbsoluteURI HTTP2 (it seems the HTTP2 specs only supports CONNECT proxying so we should probably skip this)
* [x] AbsoluteURI HTTP1

**Comment by eniolopes** [comment]
I can work on the version for http1 :)

**Comment by ericmj** [comment]
Not implementing HTTP2 proxying, see https://github.com/ericmj/xhttp/pull/50#issuecomment-444508396.
